cmake_minimum_required(VERSION 3.8)
project(tod_can_feedback_relay)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(std_msgs REQUIRED)
add_executable(tod_can_feedback_relay src/can_feedback_relay_node.cpp)
ament_target_dependencies(tod_can_feedback_relay rclcpp std_msgs)
target_compile_features(tod_can_feedback_relay PUBLIC cxx_std_17)
install(TARGETS tod_can_feedback_relay DESTINATION lib/${PROJECT_NAME})
ament_package()
